### ISSUE TITLE
`(setq last-command-event ...)` not filtered out

### ISSUE THREAD

**Issue by YorkZ** [Silex/elmacro#20]
First off, thank you very much for this package, looks super promising!

However, looks like that the function `elmacro-processor-prettify-inserts` fails to filter out the `(setq last-command-event ...)` forms in Evil. This dosent' seem to be a problem without using Evil though.

Here's a simplest example of `last-macro`:

    (defun last-macro ()
      (interactive)
      (setq last-command-event 119)          ; `w'
      (evil-forward-word-begin nil)
      (setq last-command-event 134217827)
      (setq last-command-event 'f4))

**Comment by Silex** [comment]
Ah the joys of `last-command-event` :sweat_smile: 

First, let's explain a bit how emacs works... this is what happens when you press "abc" in a buffer:

``` elisp
(setq last-command-event 97)
(self-insert-command 1)
(setq last-command-event 98)
(self-insert-command 1)
(setq last-command-event 99)
(self-insert-command 3)
```

So what `elmacro-processor-prettify-inserts` does is take pairs of these and replace it with `(insert "a")(insert "b")(insert "c")`.

Now I've tried to find out what evil does, but it's clear that it messes with normal input... and thus swallows the `self-insert-command` in order to transform them into vim motions when in normal mode, thus you are left with the `last-command-event` from the key pressed.

Maybe there's a way to know that the `last-command-event` should be ignored? it's pretty difficult, there is the same problem with `isearch`.

Well, basically suggestions are welcome :wink:

**Comment by Silex** [comment]
Btw, it'd be easy enough to add a custom processor filtering out the `last-command-event`. Ask if needed.

**Comment by YorkZ** [comment]
Thank you very much for your response. Don't worry about adding custom processor for filtering `last-command-event` because it's fairly easy.

However, I noticed that I search input hasn't been combined similar to what you did on `self-insert-command`. The following is the result of recording i-search.

    (defun last-macro ()
      (interactive)
      (isearch-forward-regexp nil 1)
      (isearch-printing-char 119 1)
      (isearch-printing-char 105 1)
      (isearch-printing-char 116 1)
      (isearch-printing-char 104 1)
      (isearch-exit))

**Comment by Silex** [comment]
Yes, it's just another example of having to handle how package X does input. For isearch it's even worse because it changed how it worked, in `24.3` it used to be something like this:

``` elisp
(defun last-macro ()
  (interactive)
  (isearch-forward-regexp nil 1)
  (setq last-command-event 119)
  (isearch-printing-char 1)
  (setq last-command-event 105)
  (isearch-printing-char 1)
  (setq last-command-event 116)
  (isearch-printing-char 1)
  (setq last-command-event 104)
  (isearch-printing-char 1)
  (isearch-exit))
```

*Ideally*, you'd want to write an `isearch-processor` that does the right transformation, then an `evil-processor`, etc. It's just too much work for me at the moment, but maybe I should take this one step at a time and create some tickets showing what needs to be done, and maybe PRs will come flowing! :smile:

**Comment by priyadarshan** [comment]
> Btw, it'd be easy enough to add a custom processor filtering out the last-command-event. Ask if needed.

Would you mind clarifying how to add a custom processor filtering out the `last-command-event`?

**Comment by Silex** [comment]
@priyadarshan: see for example https://github.com/Silex/elmacro/blob/master/elmacro.el#L104-L108

But if the goal is just to completely filter `last-command-event`, just add it to `elmacro-unwanted-commands-regexps`

**Comment by priyadarshan** [comment]
Thank you, that's perfect.

**Comment by Silex** [comment]
Hum, closing this. Reopen if needed.
